import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:ontorikkho/common_widgets/app_button.dart';
import 'package:ontorikkho/constraints/app_colors.dart';
import 'package:ontorikkho/constraints/body_text.dart';
import 'package:ontorikkho/constraints/dimensions.dart';
import 'package:ontorikkho/constraints/header_text.dart';
import '../../../../common_widgets/custom_snackbar.dart';
import '../controllers/google_authenticator_controller.dart';

class EnableGoogleAuthView extends GetView<GoogleAuthenticatorController> {
  const EnableGoogleAuthView({super.key});

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Obx(() {
        if (controller.isLoading.value) {
          return const Center(child: CircularProgressIndicator());
        }

        return SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
               SizedBox(height: AppDimensions.contentPadding.h),

              /// USER GUIDE
              Container(
                padding: EdgeInsets.all(AppDimensions.widgetPadding.r),
                decoration: BoxDecoration(
                  color: AppColors.primaryColor.withAlpha(20),
                  borderRadius: BorderRadius.circular(AppDimensions.borderRadius.r),
                ),
                child: BodyText(
                  text: "Scan the QR code with your Google Authenticator app or manually "
                      "enter the secret key below. Then enter the OTP generated by the app "
                      "to enable Two-Factor Authentication.",
                  maxLine: 10,
                  align: TextAlign.start,
                ),
              ),

               SizedBox(height: AppDimensions.sectionPadding.h),

              /// QR IMAGE
              controller.qr.value.isNotEmpty
                  ? Container(
                padding:  EdgeInsets.all(AppDimensions.widgetPadding.r),
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(AppDimensions.borderRadius.r),
                  border: Border.all(color: Colors.grey.shade300),
                ),
                child: Image.memory(
                  base64Decode(controller.qr.value.split(",").last),
                  width: 220.sp,
                  height: 220.sp,
                ),
              )
                  : const Text(
                "QR Not found!",
                style: TextStyle(color: Colors.red),
              ),

               SizedBox(height: AppDimensions.sectionPadding.h),

              /// SECRET KEY
              Container(
                padding:  EdgeInsets.symmetric(horizontal: AppDimensions.horizontalPadding.w, vertical: AppDimensions.contentPadding.h),
                decoration: BoxDecoration(
                  color: Colors.grey.shade100,
                  borderRadius: BorderRadius.circular(AppDimensions.borderRadius.r),
                  border: Border.all(color: Colors.grey.shade300),
                ),
                child: Row(
                  children: [
                    Expanded(
                      child: HeaderText(
                        text:controller.secret.value,
                      ),
                    ),
                    IconButton(
                      icon: const Icon(Icons.copy),
                      onPressed: () {
                        Clipboard.setData(
                          ClipboardData(text: controller.secret.value),
                        );
                        Get.snackbar(
                          "Copied",
                          "Secret key copied to clipboard",
                          snackPosition: SnackPosition.BOTTOM,
                        );
                      },
                    ),
                  ],
                ),
              ),

               SizedBox(height: AppDimensions.sectionPadding.h),

              /// OTP INPUT FIELD
              TextField(
                keyboardType: TextInputType.number,
                maxLength: 6,
                decoration: InputDecoration(
                  labelText: "Enter OTP from Google Authenticator",
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(AppDimensions.borderRadius.r),
                  ),
                ),
                onChanged: (v) => controller.otpValue.value = v,
              ),

               SizedBox(height: AppDimensions.sectionPadding.h),

              /// ENABLE BUTTON
              Obx(() {
                return controller.isVerifying.value
                    ? const CircularProgressIndicator()
                    : SizedBox(
                  width: double.infinity,
                  child: AppButton(
                    onTap: () async {
                      if (controller.otpValue.value.length != 6) {


                        CustomSnackBar(
                            isSuccess: false,
                            msg: "Please enter valid 6-digit OTP"
                        ).showSnackBar();
                        return;
                      }
                      await controller.enable2fa();
                    },
                    text: "Enable 2FA",
                    bgColor: AppColors.primaryColor,
                    showBorder: false,
                  ),
                );
              }),
            ],
          ),
        );
      }),
    );
  }
}
