part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LOGIN = _Paths.LOGIN;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const SPLASH_SCREEN = _Paths.SPLASH_SCREEN;
  static const REGISTRATION = _Paths.REGISTRATION;
  static const PROFILE = _Paths.PROFILE;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const EVENTS = _Paths.EVENTS;
  static const EVENT_DETAILS = _Paths.EVENT_DETAILS;
  static const PARTNER = _Paths.PARTNER;
  static const DIRECTORY = _Paths.DIRECTORY;
  static const STORE = _Paths.STORE;
  static const SHOP_DETAILS = _Paths.SHOP_DETAILS;
  static const PRODUCT_DETAILS = _Paths.PRODUCT_DETAILS;
  static const MEDIA = _Paths.MEDIA;
  static const OWN_PROFILE = _Paths.OWN_PROFILE;
  static const SETTINGS_AND_SUPPORT = _Paths.SETTINGS_AND_SUPPORT;
  static const PRIVACY = _Paths.PRIVACY;
  static const SUPPORT = _Paths.SUPPORT;
  static const PUSH_NOTIFICATION = _Paths.PUSH_NOTIFICATION;
  static const FAQ = _Paths.FAQ;
  static const IMAGE_VIEWER = _Paths.IMAGE_VIEWER;
  static const VIDEO_PLAYER = _Paths.VIDEO_PLAYER;
  static const PAYMENT_OPTIONS = _Paths.PAYMENT_OPTIONS;
  static const MEMBERSHIP_RENEW = _Paths.MEMBERSHIP_RENEW;
  static const FEVOURITE = _Paths.FEVOURITE;
  static const ANNOUNCEMENTS = _Paths.ANNOUNCEMENTS;
  static const PENDING_LIST = _Paths.PENDING_LIST;
  static const OTP = _Paths.OTP;
  static const PASSWORD = _Paths.PASSWORD;
  static const REFERENCE_MEMBER_LIST = _Paths.REFERENCE_MEMBER_LIST;
  static const USER_PERSONAL_DATA = _Paths.USER_PERSONAL_DATA;
  static const CART = _Paths.CART;
  static const CHECKOUT = _Paths.CHECKOUT;
  static const ORDER_DETAILS = _Paths.ORDER_DETAILS;
  static const SUBSCRIPRTION = _Paths.SUBSCRIPRTION;
  static const MISSING_DOCUMENTS = _Paths.MISSING_DOCUMENTS;
  static const ORDER_HISTORY = _Paths.ORDER_HISTORY;
  static const ORDER_TRACK = _Paths.ORDER_TRACK;
  static const MEMBERSHIP_PLANS = _Paths.MEMBERSHIP_PLANS;
  static const INVITE_FRIENDS = _Paths.INVITE_FRIENDS;
  static const TWO_STEP_VERIFICATION = _Paths.TWO_STEP_VERIFICATION;
  static const GOOGLE_AUTHENTICATOR = _Paths.GOOGLE_AUTHENTICATOR;
  static const EVENT_LIST = _Paths.EVENT_LIST;
  static const FOR_YOU = _Paths.FOR_YOU;
  static const CREATE_POST = _Paths.CREATE_POST;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const SETTINGS = _Paths.SETTINGS;
  static const SINGLE_POST_VIEW = _Paths.SINGLE_POST_VIEW;
  static const EDIT_POST = _Paths.EDIT_POST;
  static const PROFILE_FEED = _Paths.PROFILE_FEED;
  static const NOTIFICATION_DETAILS = _Paths.NOTIFICATION_DETAILS;
  static const SINGLE_POST_VIEW_WITH_COMMENTS =
      _Paths.SINGLE_POST_VIEW_WITH_COMMENTS;
  static const FRIENDS = _Paths.FRIENDS;
  static const PAGES = _Paths.PAGES;
  static const PAGE_FEED = _Paths.PAGE_FEED;

  static const MANAGE_ADMIN_PAGE = _Paths.MANAGE_ADMIN_PAGE;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const FORGOT_PASSWORD = '/forgot-password';
  //static const SPLASH_SCREEN = '/splash-screen';
  static const SPLASH_SCREEN = '/';
  static const REGISTRATION = '/registration';
  static const PROFILE = '/memberProfile';
  static const EDIT_PROFILE = '/edit-profile';
  static const EVENTS = '/events';
  static const EVENT_DETAILS = '/event-details';
  static const PARTNER = '/partner';
  static const DIRECTORY = '/directory';
  static const STORE = '/store';
  static const SHOP_DETAILS = '/shop-details';
  static const PRODUCT_DETAILS = '/product-details';
  static const MEDIA = '/media';
  static const OWN_PROFILE = '/own-profile';
  static const SETTINGS_AND_SUPPORT = '/settings-and-support';
  static const PRIVACY = '/privacy';
  static const SUPPORT = '/support';
  static const PUSH_NOTIFICATION = '/push-notification';
  static const FAQ = '/faq';
  static const IMAGE_VIEWER = '/image-viewer';
  static const VIDEO_PLAYER = '/video-player';
  static const PAYMENT_OPTIONS = '/payment-options';
  static const MEMBERSHIP_RENEW = '/membership-renew';
  static const FEVOURITE = '/favourite';
  static const ANNOUNCEMENTS = '/announcements';
  static const PENDING_LIST = '/pending-list';
  static const OTP = '/otp';
  static const PASSWORD = '/password';
  static const REFERENCE_MEMBER_LIST = '/reference-member-list';
  static const USER_PERSONAL_DATA = '/user-personal-data';
  static const CART = '/cart';
  static const CHECKOUT = '/checkout';
  static const ORDER_DETAILS = '/order-details';
  static const SUBSCRIPRTION = '/subscription';
  static const MISSING_DOCUMENTS = '/missing-documents';
  static const ORDER_HISTORY = '/order-history';
  static const ORDER_TRACK = '/order-track';
  static const MEMBERSHIP_PLANS = '/membership-plans';
  static const INVITE_FRIENDS = '/invite-friends';
  static const TWO_STEP_VERIFICATION = '/two-step-verification';
  static const GOOGLE_AUTHENTICATOR = '/google-authenticator';
  static const EVENT_LIST = '/event-list';
  static const FOR_YOU = '/for-you';
  static const CREATE_POST = '/create-post';
  static const NOTIFICATIONS = '/notifications';
  static const SETTINGS = '/settings';
  static const SINGLE_POST_VIEW = '/single-post-view';
  static const EDIT_POST = '/edit-post';
  static const PROFILE_FEED = '/profile-feed';
  static const NOTIFICATION_DETAILS = '/notification-details';
  static const SINGLE_POST_VIEW_WITH_COMMENTS =
      '/single-post-view-with-comments';
  static const FRIENDS = '/friends';
  static const PAGES = '/pages';
  static const PAGE_FEED = '/page-feed';

  static const MANAGE_ADMIN_PAGE = '/manage-admin';
}
